version: '3'
services: 
  python-app:
    build: py_app
    ports:
     - "5090:5000"
    volumes:
     - .:/sampleapp
    depends_on:
     - redis
    links:
     - redis
  webserver:
    build: nginx_app
    ports:
     - "8000:80"

  redis:
    build: redis_app
    ports: 
     - "6379:6379"

